/**
 * Export and Share Utilities for Food Mini-App
 * PDF generation and sharing functionality
 */

import { format } from 'date-fns';

// Types for exportable data
interface ExportableItem {
  name: string;
  quantity?: number;
  unit?: string;
  [key: string]: unknown;
}

interface MealPlanDay {
  date: string;
  breakfast?: string;
  lunch?: string;
  dinner?: string;
  snacks?: string[];
}

interface GroceryExportData {
  title: string;
  items: ExportableItem[];
  generatedAt: string;
}

interface MealPlanExportData {
  title: string;
  weekStart: string;
  weekEnd: string;
  days: MealPlanDay[];
  generatedAt: string;
}

interface InventoryExportData {
  title: string;
  items: ExportableItem[];
  location?: string;
  generatedAt: string;
}

/**
 * Generate PDF from HTML content using browser print
 */
export function generatePDF(htmlContent: string, filename: string): void {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate PDF');
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
          color: #1a1a1a;
        }
        h1 { 
          font-size: 24px; 
          margin-bottom: 8px;
          color: #22C55E;
        }
        h2 { 
          font-size: 18px; 
          margin-top: 24px;
          margin-bottom: 12px;
          color: #333;
        }
        .subtitle {
          color: #666;
          font-size: 14px;
          margin-bottom: 24px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 24px;
        }
        th, td {
          text-align: left;
          padding: 12px;
          border-bottom: 1px solid #eee;
        }
        th {
          background: #f9f9f9;
          font-weight: 600;
        }
        .checkbox {
          width: 16px;
          height: 16px;
          border: 2px solid #ccc;
          border-radius: 4px;
          display: inline-block;
        }
        .checked {
          background: #22C55E;
          border-color: #22C55E;
        }
        .meal-card {
          border: 1px solid #eee;
          border-radius: 8px;
          padding: 16px;
          margin-bottom: 12px;
        }
        .meal-day {
          font-weight: 600;
          color: #22C55E;
          margin-bottom: 8px;
        }
        .meal-slot {
          display: flex;
          gap: 8px;
          margin-bottom: 4px;
        }
        .meal-slot-label {
          font-weight: 500;
          min-width: 80px;
        }
        .footer {
          margin-top: 40px;
          padding-top: 16px;
          border-top: 1px solid #eee;
          font-size: 12px;
          color: #999;
        }
        @media print {
          body { padding: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      ${htmlContent}
      <div class="footer">
        Generated by Youmaxing on ${format(new Date(), 'PPP')}
      </div>
      <script>
        window.onload = function() {
          window.print();
          window.onafterprint = function() { window.close(); };
        };
      </script>
    </body>
    </html>
  `);
  printWindow.document.close();
}

/**
 * Generate grocery list HTML for PDF
 */
export function generateGroceryPDFContent(data: GroceryExportData): string {
  const itemRows = data.items
    .map(item => `
      <tr>
        <td><span class="checkbox"></span></td>
        <td>${item.name}</td>
        <td>${item.quantity || ''} ${item.unit || ''}</td>
      </tr>
    `)
    .join('');

  return `
    <h1>Grocery List</h1>
    <p class="subtitle">${data.title} - ${data.items.length} items</p>
    <table>
      <thead>
        <tr>
          <th style="width: 40px;"></th>
          <th>Item</th>
          <th style="width: 120px;">Quantity</th>
        </tr>
      </thead>
      <tbody>
        ${itemRows}
      </tbody>
    </table>
  `;
}

/**
 * Generate meal plan HTML for PDF
 */
export function generateMealPlanPDFContent(data: MealPlanExportData): string {
  const dayCards = data.days
    .map(day => `
      <div class="meal-card">
        <div class="meal-day">${day.date}</div>
        ${day.breakfast ? `<div class="meal-slot"><span class="meal-slot-label">Breakfast:</span> ${day.breakfast}</div>` : ''}
        ${day.lunch ? `<div class="meal-slot"><span class="meal-slot-label">Lunch:</span> ${day.lunch}</div>` : ''}
        ${day.dinner ? `<div class="meal-slot"><span class="meal-slot-label">Dinner:</span> ${day.dinner}</div>` : ''}
        ${day.snacks?.length ? `<div class="meal-slot"><span class="meal-slot-label">Snacks:</span> ${day.snacks.join(', ')}</div>` : ''}
      </div>
    `)
    .join('');

  return `
    <h1>Weekly Meal Plan</h1>
    <p class="subtitle">${data.weekStart} - ${data.weekEnd}</p>
    ${dayCards}
  `;
}

/**
 * Generate inventory HTML for PDF
 */
export function generateInventoryPDFContent(data: InventoryExportData): string {
  const itemRows = data.items
    .map(item => `
      <tr>
        <td>${item.name}</td>
        <td>${item.quantity || ''} ${item.unit || ''}</td>
        <td>${(item as any).location || ''}</td>
        <td>${(item as any).expiration_date ? format(new Date((item as any).expiration_date), 'MMM d, yyyy') : ''}</td>
      </tr>
    `)
    .join('');

  return `
    <h1>Inventory</h1>
    <p class="subtitle">${data.title} - ${data.items.length} items</p>
    <table>
      <thead>
        <tr>
          <th>Item</th>
          <th style="width: 100px;">Quantity</th>
          <th style="width: 100px;">Location</th>
          <th style="width: 120px;">Expires</th>
        </tr>
      </thead>
      <tbody>
        ${itemRows}
      </tbody>
    </table>
  `;
}

/**
 * Share content via native share API or clipboard
 */
export async function shareContent(
  title: string,
  text: string,
  url?: string
): Promise<boolean> {
  // Try native share API first (mobile/supported browsers)
  if (navigator.share) {
    try {
      await navigator.share({
        title,
        text,
        url,
      });
      return true;
    } catch (err) {
      // User cancelled or share failed
      if ((err as Error).name !== 'AbortError') {
        console.error('Share failed:', err);
      }
    }
  }

  // Fallback: copy to clipboard
  try {
    const content = url ? `${title}\n\n${text}\n\n${url}` : `${title}\n\n${text}`;
    await navigator.clipboard.writeText(content);
    return true;
  } catch (err) {
    console.error('Clipboard failed:', err);
    return false;
  }
}

/**
 * Generate shareable text for grocery list
 */
export function generateGroceryShareText(items: ExportableItem[]): string {
  return items
    .map(item => `- ${item.name}${item.quantity ? ` (${item.quantity} ${item.unit || ''})` : ''}`)
    .join('\n');
}

/**
 * Generate shareable text for meal plan
 */
export function generateMealPlanShareText(days: MealPlanDay[]): string {
  return days
    .map(day => {
      const meals = [];
      if (day.breakfast) meals.push(`  Breakfast: ${day.breakfast}`);
      if (day.lunch) meals.push(`  Lunch: ${day.lunch}`);
      if (day.dinner) meals.push(`  Dinner: ${day.dinner}`);
      if (day.snacks?.length) meals.push(`  Snacks: ${day.snacks.join(', ')}`);
      return `${day.date}\n${meals.join('\n')}`;
    })
    .join('\n\n');
}

/**
 * Generate shareable text for inventory
 */
export function generateInventoryShareText(items: ExportableItem[]): string {
  return items
    .map(item => `- ${item.name}: ${item.quantity || '?'} ${item.unit || 'items'}`)
    .join('\n');
}

